added a few more configurable options
Collaborne/animated-content-placeholder pull request #1
Opened 2017-07-13 14:06 UTC by daniel-vlad

Hi,

I've added a few more configurable options for the placeholder. Needed the component in one of our projects and having the ability to configure a few more things would have been a nice feature.
If you think this is ok and merge worthy please do so 😄 

Daniel

2017-07-13 15:49 UTC, ankon requested changes
The changes contain a lot of unneeded whitespace changes/reindentation, could you please undo these?

2017-07-13 22:31 UTC, daniel-vlad commented
will do. sorry about that, looks like vscode autoformat messed things up a bit

2017-07-14 11:37 UTC, daniel-vlad commented
Changed the indentation so that it matches the original one and added missing eof new lines

2017-07-14 13:35 UTC, ankon requested changes

2017-07-14 13:35 UTC, ankon commented on animated-content-placeholder.html
>  </animated-content-placeholder>
Hmm. 

This doesn't look right. 

Note that we're using actual tab characters, and do not replace tabs with any particular amount of spaces.

2017-07-21 10:47 UTC, merged